### PR TITLE
power monitor instability fix

### LINKED ISSUE #640: Power Monitors Unstable State
The power monitor when connected to a valid power network swaps between the connected and disconnected states.

### PR DESCRIPTION
**Pull request by SomeName42**
Fixed power monitor instability where it was switching between having and not having network infotext. Resolves #640. The cause of the issue was that the power monitor is LV MV and HV machine at the same time, and each tier has a countdown. If any of these countdowns were 0 it treated the machine as having no network. This was changed so that it only treats a machine as having no network if it is timed out in all tiers that it is a part of.

### CODE REVIEW

File: technic/machines/switching_station.lua [hunk 1]
```diff
@@ -468,22 +468,31 @@ minetest.register_abm({
...
+				technic_machine = true
+				if not switching_station_timeout_count(pos, tier) then
+					has_network = true
 				end
 			end
 		end
+
+		if technic_machine and not has_network then
+			local nodedef = minetest.registered_nodes[node.name]
+			if nodedef then
```
Comment (SmallJoker) [inline technic/machines/switching_station.lua:484]: This ABM depends on the node group, which means that the node must be registered. Hence such check should always evaluate to `true`. If not, then it's probably an engine bug.

Comment (SomeName42) [reply technic/machines/switching_station.lua:484]: Do you mean the technic_machine variable?

Comment (SmallJoker) [reply technic/machines/switching_station.lua:484]: No, I mean the line that I commented on. `if nodedef then` should (in this case) be equal to `if true then`.
